config/routes.rb
Rails.application.routes.draw do

  root 'documents#index'

  resources :documents do
    collection do
      post :search
    end
  end

end

app/models/document.rb
class Document < ActiveRecord::Base
  include Search
  has_many :tokens

  def self.searchable_fields
    %w(content)
  end
end

app/models/token.rb
class Token < ActiveRecord::Base
  belongs_to :document
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  include Parser
  before_filter :init_document, only: [:index, :search]
  def index
    @documents =  Document.all
  end

  def create
    if params[:document] && params[:document][:content].present?
      @document = Document.new(content: params[:document][:content])
      if @document.save
        message = "Document was created successfully."
      else
        message = "There was an error."
      end
    else
      message = "Document content is empty"
    end

    flash[:notice] = message
  	redirect_to documents_path
  end

  def search
    @tokens = Parser.parse_text(params[:query])
    @documents = Document.search(params[:query])
    render :index
  end

  def init_document
    @document = Document.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_document.html.erb
<tr>
  <td><%= document.id %> </td>
  <td><div class='content'><%= document.content %></div></td>
</tr>

app/views/documents/index.html.erb
<h3>Write or paste the document content</h3>

<% if flash[:notice].present? %>
  <div class="alert alert-info" role="alert"><%= flash[:notice] %></div>
<% end %>

<%= form_for(@document, class: 'navbar-form') do |f| %>
  <div class="form-group"><%= f.text_area :content, class: 'form-control', rows: 4 %></div>
  <%= submit_tag 'Submit', class: 'btn btn-default' %>
<% end %>

<br/>
<%= form_tag(search_documents_path, class: "navbar-form navbar-right", role: "search") do %>
  <%= text_field_tag :query, '', class: 'form-control' %>
  <%= submit_tag 'Search', class: 'btn btn-default' %>
<% end %>
<%= hidden_field_tag 'tokens', @tokens.join(','), id: 'tokens' if @tokens.present? %>
<div class="panel panel-default">
  <div class="panel-heading">
  	Documents
  </div>

  <!-- Table -->
  <table class="table">
    <thead>
      <tr>
        <td>Id</td>
        <td>Content<td/>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'document', collection: @documents %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fulltextsearch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">Full-Text Search</a>
      </div>
    </div>
  </nav>
  <div class="container">
  	<%= yield %>
  </div>

</body>
</html>